[[gettingstarted]]
  name = "Documentation"
  weight = 4
  identifier = "documentation"
  url = "/docs/"

[[configure]]
  name = "Configuring Owncast"
  weight = 10
  identifier = "config"
  url = "/docs/configuration/"

[[integrations]]
  name = "APIs and Integrations"
  weight = 200
  identifier = "integrations"
  url = "/docs/integrations/"

[[main]]
  name = "Quickstart"
  url = "/quickstart/"
  weight = 10

[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 20

[[main]]
  name = "Directory"
  url = "https://directory.owncast.online"
  weight = 40

[[main]]
  name = "Releases"
  url = "/releases"
  weight = 30


[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/owncast"
  post = "v0.1.0"
  weight = 20

[[social]]
  name = "Rocket.Chat"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-message-circle\"><path d=\"M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z\"></path></svg>"
  url = "https://owncast.rocket.chat"
  weight = 30

[[quickstart]]
  name = "Quickstart"
  weight = 10
  identifier = "quickstart"
  url = "/quickstart/"

# [[footer]]
#   name = "Contact"
#   url = "/contact"
#   weight = 10

# [[footer]]
#   name = "Contribute"
#   url = "/contribute"
#   weight = 10

# [[footer]]
#   name = "FAQ"
#   url = "/faq"
#   weight = 10