baseURL = "http://owncast.github.io/"
languageCode = "en-us"
title = "Owncast"
theme = "book"

enableGitInfo = true

[params]
    BookMenuBundle = "/menu"
    BookLogo = "/images/logo.png"
    BookRepo = "https://github.com/owncast/owncast.github.io"
    BookEditPath = "edit/master/content"
    BookComments = false