baseURL = "http://owncast.online/"
languageCode = "en-us"
title = "Owncast"
theme = "book"

enableGitInfo = true

[params]
    title = "Owncast"
    description = "A self-hosted live video and web chat server for use with existing popular broadcasting software."
    images = ["images/logo.png"]
    BookMenuBundle = "/menu"
    BookLogo = "/favicon.png"
    BookRepo = "https://github.com/owncast/owncast.github.io"
    BookEditPath = "edit/master/content"
    BookComments = false