name: Broken Links Check

on:
  workflow_dispatch:
  schedule:
    - cron: "3 3 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    if: github.repository == 'owncast/owncast.github.io'

    defaults:
      run:
        working-directory: ./scripts/linkchecker

    steps:
      - name: Check out web site code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download lychee
        run: |
          wget https://github.com/lycheeverse/lychee/releases/download/v0.14.3/lychee-v0.14.3-x86_64-unknown-linux-gnu.tar.gz && tar xvf lychee-v0.14.3-x86_64-unknown-linux-gnu.tar.gz

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Run link checker
        run: ./run.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
