name: Hugo Build to GitHub Pages

on:
  push:
    branches:
    - 'master'
  schedule:
    # Every six hours update the web site
    - cron:  '0 */6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          extended: true

      - name: Fetch Collaborators
        run: curl https://api.github.com/repos/owncast/owncast/contributors > data/collaborators.json

      - name: Add current development documentation
        run: mkdir -p static/api/development && curl https://raw.githubusercontent.com/owncast/owncast/master/doc/api/index.html > static/api/development/index.html

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Owncast
          author_email: owncast@owncast.online
          message: "Update dynamic content"
          add: "static/api/development/index.html data/collaborators.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
